export const colorLogo1 = "#A29C9C";
export const colorLogo2 = "#EEE6E6";
export const colorWhite = "#FFFFFF";
export const colorBlack = "#000000"
export const fontFira = "'Fira Sans Extra Condensed', sans-serif";
export const fontPlay = "'Playfair Display', serif";
export const fontMavenPro = "'Maven Pro', sans-serif";
export const tabletL = "1024px";
export const tabletS = "900px";
export const fonoL = "768px";
export const fonoS = "600px";
